# Generated by Django 3.0.8 on 2021-07-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_uploadsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsong',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
